"""Ajout champ mot_de_passe a Client

Revision ID: 2871ff5bc196
Revises: 6f808ce137a8
Create Date: 2025-12-11 15:24:29.928920

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2871ff5bc196'
down_revision: Union[str, Sequence[str], None] = '6f808ce137a8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clients', sa.Column('mot_de_passe', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('clients', 'mot_de_passe')
    # ### end Alembic commands ###
