"""Ajout des colonnes temporelles

Revision ID: 48811cf8d7fc
Revises: f4b47a5df4fe
Create Date: 2025-12-16 17:05:11.220698

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '48811cf8d7fc'
down_revision: Union[str, Sequence[str], None] = 'f4b47a5df4fe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('admins', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('admins', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.add_column('clients', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('clients', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.add_column('locations', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.add_column('vehicules', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('vehicules', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.alter_column('vehicules', 'prix_journalier',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('vehicules', 'prix_journalier',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('vehicules', 'updated_at')
    op.drop_column('vehicules', 'created_at')
    op.drop_column('locations', 'updated_at')
    op.drop_column('clients', 'updated_at')
    op.drop_column('clients', 'created_at')
    op.drop_column('admins', 'updated_at')
    op.drop_column('admins', 'created_at')
    # ### end Alembic commands ###
