"""Initial migration

Revision ID: 6f808ce137a8
Revises: 
Create Date: 2025-12-10 13:27:44.669358

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6f808ce137a8'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('locations', sa.Column('date_debut', sa.Date(), nullable=True))
    op.add_column('locations', sa.Column('date_fin', sa.Date(), nullable=True))
    op.drop_column('locations', 'duree')
    op.add_column('vehicules', sa.Column('prix_journalier', sa.Integer(), nullable=True))
    op.drop_column('vehicules', 'cylindree')
    op.drop_column('vehicules', 'nbre_portes')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vehicules', sa.Column('nbre_portes', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('vehicules', sa.Column('cylindree', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('vehicules', 'prix_journalier')
    op.add_column('locations', sa.Column('duree', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('locations', 'date_fin')
    op.drop_column('locations', 'date_debut')
    # ### end Alembic commands ###
