"""ajout champ prix_total

Revision ID: a3d2d3a26d77
Revises: c1654301c43d
Create Date: 2026-02-05 16:44:00.994938

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a3d2d3a26d77'
down_revision: Union[str, Sequence[str], None] = 'c1654301c43d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('locations', sa.Column('prix_total', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('locations', 'prix_total')
    # ### end Alembic commands ###
