"""ajout de la colonne duree

Revision ID: c1654301c43d
Revises: 4402c0c8287b
Create Date: 2026-02-05 16:00:42.717578

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c1654301c43d'
down_revision: Union[str, Sequence[str], None] = '4402c0c8287b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('locations', sa.Column('duree', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('locations', 'duree')
    # ### end Alembic commands ###
