"""ajout du champ statut a location

Revision ID: f4b47a5df4fe
Revises: 2871ff5bc196
Create Date: 2025-12-12 21:05:21.426891

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f4b47a5df4fe'
down_revision: Union[str, Sequence[str], None] = '2871ff5bc196'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('locations', sa.Column('statut', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('locations', 'statut')
    # ### end Alembic commands ###
